[basic]
task_mode = "single_task"    # single_task or batch_tasks
max_time_step = 20           # For all tasks, set the maximum step length
save_screenshots = true  # screenshots
screenshot_path = "./screenshots"

[model]
json_model_response = false      # Whether to require a model to strictly output json format, currently only support OPENAI models.
json_models = ["gpt-4-turbo",
                   "gpt-4-turbo-2024-04-09",
                   "gpt-4-0125-preview",
                   "gpt-4-1106-preview",
                   "gpt-3.5-turbo",
                   "gpt-3.5-turbo-0125",
                   "gpt-4o-2024-08-06",
                   "gpt-4.1",
                   "o4-mini",
                   "gpt-4.1-2025-04-14",
                   "o3-mini-2025-01-31",
                   "computer-use-preview-2025-03-11"  # OpenAI Operator correct model name
                   ]

[rag]
enabled = true          # Whether to enable RAG mode (true/false)
rag_path = "./data/Online-Mind2Web/rag_data"    # Path to store RAG data

# OpenAI Operator specific settings
[operator]
enabled = true                           # Whether to enable OpenAI Operator
model_name = "computer-use-preview-2025-03-11"  # Correct operator model name
max_image_dimension = 1200              # Maximum image dimension for operator
screenshot_optimization = true          # Whether to optimize screenshots for operator
rag_integration = true                  # Whether to integrate RAG with operator

[steps]
interaction_mode = false            #  Whether human control of task execution status is required
single_task_action_step = 20     
batch_tasks_max_action_step =25
batch_tasks_condition_step_increase = 5

[files]
batch_tasks_file_path = "./data/Online-Mind2Web/72exp30.json" # The input data path
ground_truth_file_path = "./data/human_labeled_reward_reference/GT_instructions_202404161811_for_all_data_0328.json"  # the ground_truth data path
out_file_path = "./test/exp"   # YOUR OUT FILE PATH 

[conditions]
URL = ["error"]

[token_pricing]
pricing_models = [
    "gpt-4o",
    "gpt-4o-2024-08-06",
    "gpt-4.1",
    "gpt-4o-mini",
    "gpt-4o-mini-2024-07-18",
    "gpt-4-turbo",
    "gpt-4-turbo-2024-04-09",
    "gpt-4",
    "gpt-4-32k",
    "gpt-4-0125-preview",
    "gpt-4-1106-preview",
    "gpt-4-vision-preview",
    "gpt-3.5-turbo-0125",
    "gpt-3.5-turbo-1106",
    "o4-mini",
    "computer-use-preview-2025-03-11"  # Add correct operator model for token pricing
    ]

# The price of each model for input and output, the unit is $/token
# The name of input token price: model_name + "_input_price", such as gpt-4o_input_price
# The name of output token price: model_name + "_output_price", such as gpt-4o_output_price
gpt-4o-2024-08-06_input_price       = 0.000005
gpt-4o-2024-08-06_output_price      = 0.000015
gpt-4.1_input_price                 = 0.000005
gpt-4.1_output_price                = 0.000015
gpt-4o_input_price                  = 0.000005
gpt-4o_output_price                 = 0.000015
gpt-4o-2024-05-13_input_price       = 0.000005
gpt-4o-2024-05-13_output_price      = 0.000015
gpt-4o-mini_input_price             = 0.00000015
gpt-4o-mini_output_price            = 0.0000006
gpt-4o-mini-2024-07-18_input_price  = 0.00000015
gpt-4o-mini-2024-07-18_output_price = 0.0000006
gpt-4-turbo_input_price             = 0.00001
gpt-4-turbo_output_price            = 0.00003
gpt-4-turbo-2024-04-09_input_price  = 0.00001
gpt-4-turbo-2024-04-09_output_price = 0.00003
gpt-4_input_price                   = 0.00003
gpt-4_output_price                  = 0.00006
gpt-4-32k_input_price               = 0.00006
gpt-4-32k_output_price              = 0.00012
gpt-4-0125-preview_input_price      = 0.00001
gpt-4-0125-preview_output_price     = 0.00003
gpt-4-1106-preview_input_price      = 0.00001
gpt-4-1106-preview_output_price     = 0.00003
gpt-4-vision-preview_input_price    = 0.00001
gpt-4-vision-preview_output_price   = 0.00003
gpt-3.5-turbo-0125_input_price      = 0.0000005
gpt-3.5-turbo-0125_output_price     = 0.0000015
gpt-3.5-turbo-1106_input_price      = 0.000001
gpt-3.5-turbo-1106_output_price     = 0.000002
o4-mini                             = 0.000002
computer-use-preview-2025-03-11     = 0.000005
# OpenAI Operator pricing (estimated - adjust based on actual pricing)
computer-use-preview-2025-03-11_input_price  = 0.00001
computer-use-preview-2025-03-11_output_price = 0.00003